"""
Django settings for BankersAlgorithm project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oyf0^2#h968ym7mrx9qw1*w40fl6nm#v+ouv^d1^l0s#idql3q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
STATIC_ROOT = '/home/BankersAlgorithm/nginx/static/'


ALLOWED_HOSTS = ['47.113.218.219', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'information',
    'timethinker',
    'useroperation',
    'mainpage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BankersAlgorithm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BankersAlgorithm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    (os.path.join(BASE_DIR, 'static'))
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 后台管理界面优化
SIMPLEUI_INDEX = '/'
SIMPLEUI_HOME_INFO = False 
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_ICON = False
SIMPLEUI_DEFAULT_THEME = 'purple.css' # 默认主题设置

# 左侧菜单自定义
SIMPLEUI_CONFIG = {
    'system_keep':  False,
    'dynamic': True, # 动态开启
    'menu_display': ['资源管理', '进程管理', '认证和授权'], # 父菜单列表
    'menus': [
        # 子菜单列表
        {
            'name': '资源管理', # 父名称设置
            'icon': 'fas fa-user-graduate', # 图标设置
            'models': [
                {
                    'name': '资源信息表', # 子名称设置
                    'icon': 'fa fa-users', # 图标设置
                    'url': 'information/resource/', # 链接到model，由model映射到数据库
                },
            ]
        },
        # 同上
        {
            'name': '进程管理',
            'icon': 'fas fa-chalkboard-teacher',
            'models': [
                {
                    'name': '进程信息表',
                    'icon': 'fa fa-users',
                    'url': 'information/process/'
                },
                {
                    'name': '最大需求矩阵表',
                    'icon': 'fa fa-list-alt',
                    'url': 'information/max/'
                },
                {
                    'name': '需求矩阵表',
                    'icon': 'fas fa-edit',
                    'url': 'information/need/'
                },
                {
                    'name': '分配矩阵表',
                    'icon': 'fas fa-bed',
                    'url': 'information/allocation/'
                },
            ]
        },
        {
            'name': '认证和授权',
            'icon': 'fa fa-cogs',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fas fa-fingerprint',
                    'url': 'auth/user/'
                },
                {
                    'name': '权限分组',
                    'icon': 'fa fa-users-cog',
                    'url': 'auth/group/'
                },
            ]
        },
    ]
}
