# Generated by Django 3.2.8 on 2022-03-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='pro_id',
            new_name='pro',
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='res_id',
            new_name='res',
        ),
        migrations.RenameField(
            model_name='need',
            old_name='pro_id',
            new_name='pro',
        ),
        migrations.RenameField(
            model_name='need',
            old_name='res_id',
            new_name='res',
        ),
        migrations.RenameField(
            model_name='rescource',
            old_name='re_id',
            new_name='res_id',
        ),
    ]
