# Generated by Django 3.2.8 on 2022-03-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20220310_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Max',
            fields=[
                ('max_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('max_num', models.IntegerField(verbose_name='已分配数')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='information.process', verbose_name='进程')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='information.rescource', verbose_name='资源')),
            ],
            options={
                'verbose_name_plural': '最大需求矩阵',
                'db_table': 'max',
                'managed': True,
            },
        ),
    ]
