# Generated by Django 3.2.8 on 2022-03-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_max'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rescource',
            new_name='Resource',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
    ]
