# Generated by Django 3.2.8 on 2022-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20220312_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='time_left',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='剩余时间'),
        ),
    ]
