# Generated by Django 3.2.8 on 2022-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_allocation_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allo_id',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
