# Generated by Django 3.2.8 on 2022-03-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_alter_allocation_allo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allo_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
