# Generated by Django 3.2.8 on 2022-03-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_alter_allocation_allo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='idx',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
