# Generated by Django 3.2.8 on 2022-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_remove_allocation_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='idx',
            field=models.CharField(default=1, editable=False, max_length=1),
            preserve_default=False,
        ),
    ]
